---
# tasks file for mariadb
- name: Install 'mariadb-server' and 'MySQL-python' packages
  yum:
    name: "{{ packages }}"
    update_cache: true
    state: present
  loop:
    - mariadb-server
    - MySQL-python
  loop_control:
    loop_var: packages
- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true
