---
# tasks file for php
- name: Put repo files to /etc/yum.repos.d/ directory
  copy:
    src: "{{ repo_files }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "*.repo"
  loop_control:
    loop_var: repo_files

- name: Install packages from 'php_packages_list'
  yum:
    name: "{{ php_packages }}"
    update_cache: true
    state: present
  loop: "{{ php_packages_list }}"
  loop_control:
    loop_var: php_packages

- name: Start php-fpm Service
  service:
    name: php-fpm
    state: started
    enabled: true
