---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: homework
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:      
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - name: mysql              
              containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD            
            valueFrom: 
              secretKeyRef: 
                key: mysql_passwd 
                name: mysql-secrets
            
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
            
      volumes:
        - name: initdb
          configMap:
            name: initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
  namespace: homework
data:
  initdb.sql: |
    CREATE DATABASE homework CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
    GRANT ALL ON homework.* TO 'user'@'%';
    FLUSH PRIVILEGES;
    USE homework;
    create table articles (id int auto_increment primary key,title text null comment 'aritcle name', text  text null comment 'article text');
    INSERT INTO homework.articles (id, title, text) VALUES (1, 'title  1', 'article text 1');
    INSERT INTO homework.articles (id, title, text) VALUES (2, 'title  2', 'article text 2');
    INSERT INTO homework.articles (id, title, text) VALUES (3, 'title  3', 'article text 3');
    INSERT INTO homework.articles (id, title, text) VALUES (4, 'title  4', 'article text 4');
    INSERT INTO homework.articles (id, title, text) VALUES (5, 'title  5', 'article text 5');


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: homework
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
